"use client";

import * as React from "react";
import type { Lead, LeadStatus, WebsiteSignal } from "@/lib/types";
import {
  Badge,
  Banner,
  Button,
  Card,
  EmptyState,
  Input,
  PageHeader,
  Spinner,
  Textarea,
  useFlash,
} from "@/app/components/ui";

const CATEGORIES = [
  { slug: "", label: "All industries", emoji: "" },
  { slug: "barbershops", label: "Barbershops", emoji: "✂️" },
  { slug: "salons-spas", label: "Salons & Spas", emoji: "💅" },
  { slug: "restaurants-cafes", label: "Restaurants & Cafes", emoji: "🍕" },
  { slug: "home-services", label: "Home Services", emoji: "🛠️" },
  { slug: "auto-repair", label: "Automotive Repair", emoji: "🚗" },
];

const STATUS_LABELS: Record<LeadStatus, string> = {
  not_contacted: "Not Contacted",
  in_outreach: "In Outreach",
  closed: "Closed",
  skipped: "Skipped",
};

const SIGNAL_LABELS: Record<WebsiteSignal, string> = {
  no_website_field: "No website",
  social_only: "Social page only",
  directory_only: "Directory listing only",
  has_website: "Has a website",
  unknown: "Unverified",
};

/**
 * A record is only trustworthy if it came from a real provider. The mock
 * provider fabricates plausible-looking businesses for testing, so those are
 * flagged loudly — acting on them would mean cold-calling strangers.
 */
function isSynthetic(lead: Lead): boolean {
  return lead.source === "mock";
}

function statusColor(status: LeadStatus): "green" | "gray" | "red" {
  if (status === "closed") return "green";
  if (status === "skipped") return "red";
  return "gray";
}

function LeadRow({
  lead,
  active,
  onSelect,
}: {
  lead: Lead;
  active: boolean;
  onSelect: (lead: Lead) => void;
}) {
  return (
    <button
      onClick={() => onSelect(lead)}
      className={`flex w-full items-center gap-3 border-b border-border px-4 py-3 text-left transition-colors last:border-0 ${
        active ? "bg-card-hover" : "hover:bg-card-hover"
      }`}
    >
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="truncate text-sm font-medium">{lead.name}</span>
          {isSynthetic(lead) && (
            <span className="shrink-0 rounded bg-amber-500/15 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-amber-500">
              Test data
            </span>
          )}
        </div>
        <p className="truncate text-xs text-muted">
          {lead.city}, {lead.state} · {SIGNAL_LABELS[lead.website_signal]}
        </p>
      </div>
      <Badge color={statusColor(lead.lead_status)}>{STATUS_LABELS[lead.lead_status]}</Badge>
    </button>
  );
}

function LeadDetail({
  lead,
  onSaved,
}: {
  lead: Lead;
  onSaved: (lead: Lead) => void;
}) {
  const [status, setStatus] = React.useState<LeadStatus>(lead.lead_status);
  const [notes, setNotes] = React.useState(lead.notes ?? "");
  const [contact, setContact] = React.useState(lead.contact_name ?? "");
  const [saving, setSaving] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    setStatus(lead.lead_status);
    setNotes(lead.notes ?? "");
    setContact(lead.contact_name ?? "");
    setError(null);
  }, [lead]);

  async function save(next: Partial<{ lead_status: LeadStatus; notes: string; contact_name: string }>) {
    setSaving(true);
    setError(null);
    const res = await fetch(`/api/leads/${lead.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(next),
    });
    const data = await res.json().catch(() => ({}));
    setSaving(false);
    if (!res.ok) {
      setError(typeof data.error === "string" ? data.error : "Could not save.");
      return;
    }
    onSaved(data.lead as Lead);
  }

  const dirty = notes !== (lead.notes ?? "") || contact !== (lead.contact_name ?? "");

  return (
    <div className="space-y-4 p-5">
      {isSynthetic(lead) && (
        <Banner kind="error">
          <strong>Synthetic test record.</strong> This business was generated by the
          finder&rsquo;s mock provider — the name, address, and phone number are not
          real. Do not contact it. Real leads require a Google Places API key.
        </Banner>
      )}

      <div>
        <h2 className="text-lg font-semibold tracking-tight">{lead.name}</h2>
        <p className="text-sm text-muted">
          {[lead.street, lead.city, lead.state, lead.postal_code].filter(Boolean).join(", ")}
        </p>
      </div>

      {lead.photos?.length > 0 && (
        <div className="flex gap-2 overflow-x-auto">
          {lead.photos.slice(0, 4).map((photo, i) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={i}
              src={photo.url}
              alt={photo.caption ?? lead.name}
              className="h-24 w-32 shrink-0 rounded-md object-cover"
            />
          ))}
        </div>
      )}

      <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
        <dt className="text-muted">Web presence</dt>
        <dd className="text-right">{SIGNAL_LABELS[lead.website_signal]}</dd>
        <dt className="text-muted">Phone</dt>
        <dd className="text-right">{lead.phone ?? "—"}</dd>
        <dt className="text-muted">Rating</dt>
        <dd className="text-right">
          {lead.rating ? `${lead.rating} (${lead.review_count ?? 0})` : "—"}
        </dd>
        <dt className="text-muted">Source</dt>
        <dd className="text-right">{lead.source.replace(/_/g, " ")}</dd>
      </dl>

      {lead.summary?.text && (
        <Card className="p-4">
          <p className="mb-1 text-xs font-medium uppercase tracking-wider text-muted">
            Investigation summary
          </p>
          <p className="whitespace-pre-line text-sm text-muted">{lead.summary.text}</p>
          {lead.summary.pitchAngle && (
            <p className="mt-2 text-sm">
              <span className="font-medium">Pitch: </span>
              {lead.summary.pitchAngle}
            </p>
          )}
        </Card>
      )}

      {error && <Banner kind="error">{error}</Banner>}

      <div>
        <p className="mb-2 text-xs font-medium uppercase tracking-wider text-muted">
          Lead status
        </p>
        <div className="flex flex-wrap gap-2">
          {(Object.keys(STATUS_LABELS) as LeadStatus[]).map((s) => (
            <button
              key={s}
              disabled={saving}
              onClick={() => {
                setStatus(s);
                void save({ lead_status: s });
              }}
              className={`rounded-md border px-3 py-1.5 text-sm transition-colors disabled:opacity-50 ${
                status === s
                  ? "border-foreground bg-foreground text-background"
                  : "border-border text-muted hover:bg-card-hover"
              }`}
            >
              {STATUS_LABELS[s]}
            </button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        <Input
          value={contact}
          onChange={(e) => setContact(e.target.value)}
          placeholder="Primary contact name"
        />
        <Textarea
          rows={3}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Outreach notes…"
        />
        <Button
          variant="ghost"
          loading={saving}
          disabled={!dirty || saving}
          onClick={() => void save({ notes, contact_name: contact })}
        >
          Save notes
        </Button>
      </div>
    </div>
  );
}

export default function LeadsPage() {
  const [leads, setLeads] = React.useState<Lead[]>([]);
  const [total, setTotal] = React.useState(0);
  const [loading, setLoading] = React.useState(true);
  const [missing, setMissing] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [flash, setFlash] = useFlash();

  const [category, setCategory] = React.useState("");
  const [status, setStatus] = React.useState("");
  const [search, setSearch] = React.useState("");
  const [debounced, setDebounced] = React.useState("");
  const [selected, setSelected] = React.useState<Lead | null>(null);

  React.useEffect(() => {
    const t = setTimeout(() => setDebounced(search), 300);
    return () => clearTimeout(t);
  }, [search]);

  const query = React.useMemo(() => {
    const p = new URLSearchParams();
    if (category) p.set("category", category);
    if (status) p.set("status", status);
    if (debounced.trim()) p.set("q", debounced.trim());
    return p.toString();
  }, [category, status, debounced]);

  React.useEffect(() => {
    let cancelled = false;
    fetch(`/api/leads?${query}`)
      .then(async (res) => {
        const data = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(data.error ?? "Could not load leads.");
        return data;
      })
      .then((data) => {
        if (cancelled) return;
        setLeads(data.leads ?? []);
        setTotal(data.total ?? 0);
        setMissing(Boolean(data.missing));
        setError(null);
        setLoading(false);
      })
      .catch((e: Error) => {
        if (cancelled) return;
        setError(e.message);
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [query]);

  function handleSaved(updated: Lead) {
    setLeads((current) => current.map((l) => (l.id === updated.id ? updated : l)));
    setSelected(updated);
    setFlash("Saved");
  }

  const syntheticCount = leads.filter(isSynthetic).length;

  return (
    <div className="p-6">
      <PageHeader
        title="Leads"
        description="US businesses with no website of their own, surfaced by the Offline Business Finder."
      />

      {flash && <Banner kind="success">{flash}</Banner>}
      {error && <Banner kind="error">{error}</Banner>}

      {missing && (
        <Banner kind="error">
          No <code>businesses</code> table found in Supabase. Run the Offline Business
          Finder&rsquo;s migration (<code>npm run db:migrate</code>) against this database
          first.
        </Banner>
      )}

      {syntheticCount > 0 && (
        <Banner kind="error">
          <strong>
            {syntheticCount} of the {leads.length} leads shown are synthetic test records.
          </strong>{" "}
          They came from the finder&rsquo;s mock provider and are not real businesses — the
          phone numbers belong to no one. Set <code>GOOGLE_PLACES_API_KEY</code> in the
          finder and re-run ingestion to replace them with real data.
        </Banner>
      )}

      <div className="mb-4 mt-4 flex flex-wrap gap-2">
        <div className="min-w-56 flex-1">
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search name, city, state, or ZIP…"
          />
        </div>
        <select
          value={category}
          onChange={(e) => setCategory(e.target.value)}
          className="h-9 rounded-md border border-border bg-background px-3 text-sm text-foreground"
        >
          {CATEGORIES.map((c) => (
            <option key={c.slug} value={c.slug}>
              {c.emoji} {c.label}
            </option>
          ))}
        </select>
        <select
          value={status}
          onChange={(e) => setStatus(e.target.value)}
          className="h-9 rounded-md border border-border bg-background px-3 text-sm text-foreground"
        >
          <option value="">Any status</option>
          {(Object.keys(STATUS_LABELS) as LeadStatus[]).map((s) => (
            <option key={s} value={s}>
              {STATUS_LABELS[s]}
            </option>
          ))}
        </select>
      </div>

      {loading ? (
        <div className="flex items-center gap-2 py-16 text-sm text-muted">
          <Spinner className="h-4 w-4" />
          Loading leads…
        </div>
      ) : leads.length === 0 ? (
        <EmptyState
          title="No leads yet"
          description="Run an ingestion sweep in the Offline Business Finder to populate this list."
        />
      ) : (
        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]">
          <Card className="overflow-hidden">
            <div className="border-b border-border px-4 py-2 text-xs text-muted">
              Showing {leads.length} of {total}
            </div>
            <div className="max-h-[65vh] overflow-y-auto">
              {leads.map((lead) => (
                <LeadRow
                  key={lead.id}
                  lead={lead}
                  active={selected?.id === lead.id}
                  onSelect={setSelected}
                />
              ))}
            </div>
          </Card>

          <Card className="overflow-hidden">
            {selected ? (
              <LeadDetail lead={selected} onSaved={handleSaved} />
            ) : (
              <div className="p-10">
                <EmptyState
                  title="Select a lead"
                  description="Pick a business on the left to see its profile and work the outreach."
                />
              </div>
            )}
          </Card>
        </div>
      )}
    </div>
  );
}
